# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 17:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('openid_provider', '0006_v2'),
		('aiakos', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='user',
			name='_oauth_post_logout_redirect_uris',
			field=models.TextField(blank=True, help_text='Enter each URI on a new line.', verbose_name='post-logout redirect URIs'),
		),
		migrations.AddField(
			model_name='user',
			name='_oauth_redirect_uris',
			field=models.TextField(blank=True, help_text='Enter each URI on a new line.', verbose_name='redirect URIs'),
		),
		migrations.AddField(
			model_name='user',
			name='oauth_allow_wildcard_redirect',
			field=models.BooleanField(default=False, verbose_name='allow wildcards in redirect URIs'),
		),
		migrations.AddField(
			model_name='user',
			name='oauth_app',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_account_set', to='openid_provider.App', verbose_name='application'),
		),
		migrations.AddField(
			model_name='user',
			name='oauth_application_type',
			field=models.CharField(choices=[('web', 'Web application'), ('native', 'Native application')], default='web', max_length=50, verbose_name='application type'),
		),
		migrations.AddField(
			model_name='user',
			name='oauth_auth_method',
			field=models.CharField(choices=[('none', 'No authentication'), ('client_secret_basic', 'HTTP Basic authentication'), ('client_secret_post', 'Client credentials in the request body')], default='client_secret_basic', max_length=50, verbose_name='authentication method'),
		),
		migrations.AddField(
			model_name='user',
			name='oauth_software_id',
			field=models.CharField(blank=True, max_length=100, verbose_name='software id'),
		),
		migrations.AddField(
			model_name='user',
			name='oauth_software_version',
			field=models.CharField(blank=True, max_length=100, verbose_name='software version'),
		),
	]
