# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('aiakos', '0002_oauth'),
	]

	operations = [
		migrations.RemoveField(
			model_name='user',
			name='name',
		),
		migrations.RemoveField(
			model_name='user',
			name='nickname',
		),
		migrations.AddField(
			model_name='user',
			name='family_name',
			field=models.CharField(blank=True, max_length=200, verbose_name='family name'),
		),
		migrations.AddField(
			model_name='user',
			name='given_name',
			field=models.CharField(blank=True, max_length=200, verbose_name='given name'),
		),
		migrations.AddField(
			model_name='user',
			name='middle_name',
			field=models.CharField(blank=True, max_length=200, verbose_name='middle name'),
		),
	]
