# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 15:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trusted', models.BooleanField(default=False)),
                ('sub', models.CharField(max_length=200)),
                ('userinfo_yaml', models.TextField(blank=True, verbose_name='User information')),
            ],
            options={
                'verbose_name_plural': 'External identities',
            },
        ),
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Example: accounts.google.com; may include a path', max_length=150, unique=True, verbose_name='domain')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('client_id', models.CharField(blank=True, max_length=150)),
                ('client_secret', models.TextField(blank=True)),
                ('protocol', models.CharField(blank=True, choices=[('openid_connect', 'OpenID Connect'), ('github', 'github'), ('gitlab', 'gitlab')], default='openid_connect', max_length=50, verbose_name='protocol')),
                ('protocol_settings_yaml', models.TextField(blank=True, help_text='In YAML. Usually empty.', verbose_name='protocol-specific settings')),
                ('inherit_admin_status', models.BooleanField(default=False, help_text="Grant superuser status to the provider's admins.")),
            ],
        ),
        migrations.AddField(
            model_name='externalidentity',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_extauth.IdentityProvider'),
        ),
        migrations.AddField(
            model_name='externalidentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='externalidentity',
            unique_together=set([('sub', 'provider')]),
        ),
    ]
