# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=200)),
                ('userinfo_yaml', models.TextField(default='', verbose_name='User information')),
            ],
            options={
                'verbose_name_plural': 'External identities',
            },
        ),
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('url', models.URLField(verbose_name='URL')),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('legacy_protocol', models.CharField(blank=True, choices=[('github', 'github'), ('gitlab', 'gitlab')], max_length=50)),
                ('legacy_settings_yaml', models.TextField(blank=True, help_text='Legacy protocol specific settings, in YAML. Usually empty.', verbose_name='Legacy protocol settings')),
                ('inherit_admin_status', models.BooleanField(default=False, help_text="Grant superuser status to the provider's admins.")),
            ],
        ),
        migrations.AddField(
            model_name='externalidentity',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_extauth.IdentityProvider'),
        ),
        migrations.AddField(
            model_name='externalidentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='externalidentity',
            unique_together=set([('provider', 'sub')]),
        ),
    ]
