# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_extauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identityprovider',
            old_name='legacy_protocol',
            new_name='protocol',
        ),
        migrations.RenameField(
            model_name='identityprovider',
            old_name='legacy_settings_yaml',
            new_name='protocol_settings_yaml',
        ),
        migrations.RenameField(
            model_name='identityprovider',
            old_name='url',
            new_name='domain',
        ),
        migrations.AddField(
            model_name='externalidentity',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='domain',
            field=models.CharField(default='', help_text='Example: accounts.google.com; may include a path', max_length=200, unique=True, verbose_name='domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='protocol',
            field=models.CharField(blank=True, choices=[('openid_connect', 'OpenID Connect'), ('github', 'github'), ('gitlab', 'gitlab')], default='openid_connect', max_length=50, verbose_name='protocol'),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='protocol_settings_yaml',
            field=models.TextField(blank=True, help_text='In YAML. Usually empty.', verbose_name='protocol-specific settings'),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='client_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='client_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='identityprovider',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='externalidentity',
            unique_together=set([('sub', 'provider')]),
        ),
    ]
