# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('given_name', models.CharField(blank=True, max_length=200)),
                ('family_name', models.CharField(blank=True, max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('preferred_username', models.CharField(blank=True, max_length=200)),
                ('picture', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('zoneinfo', models.CharField(blank=True, max_length=200)),
                ('locale', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('address_formatted', models.TextField(blank=True)),
                ('address_street', models.TextField(blank=True)),
                ('address_locality', models.TextField(blank=True)),
                ('address_region', models.TextField(blank=True)),
                ('address_postal_code', models.TextField(blank=True)),
                ('address_country', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
