# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('openid_provider', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='client',
			name='_trusted_scopes',
			field=models.TextField(blank=True, default='', verbose_name='trusted scopes'),
		),
	]
