# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('openid_provider', '0002_client__trusted_scopes'),
	]

	operations = [
		migrations.AddField(
			model_name='client',
			name='allow_wildcard_redirect',
			field=models.BooleanField(default=False, verbose_name='allow wildcards in redirect URIs'),
		),
	]
