# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('openid_provider', '0003_client_allow_wildcard_redirect'),
	]

	operations = [
		migrations.AddField(
			model_name='client',
			name='_post_logout_redirect_uris',
			field=models.TextField(blank=True, help_text='Enter each URI on a new line.', verbose_name='post-logout redirect URIs'),
		),
		migrations.AlterField(
			model_name='client',
			name='_redirect_uris',
			field=models.TextField(help_text='Enter each URI on a new line.', verbose_name='redirect URIs'),
		),
	]
