# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 16:49
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('openid_provider', '0005_drop'),
	]

	operations = [
		migrations.CreateModel(
			name='AccessToken',
			fields=[
				('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
				('expires_at', models.DateTimeField()),
				('_scope', models.TextField(default='')),
				('confidential', models.BooleanField()),
				('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='App',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
				('uri', models.URLField(blank=True, verbose_name='homepage URL')),
				('initiate_login_uri', models.URLField(blank=True, verbose_name='login initiation URL')),
				('logo_uri', models.URLField(blank=True, verbose_name='logo URL')),
				('tos_uri', models.URLField(blank=True, verbose_name='terms of service URL')),
				('policy_uri', models.URLField(blank=True, verbose_name='privacy policy URL')),
				('_contacts', models.TextField(blank=True, verbose_name='contact e-mails')),
				('_trusted_scopes', models.TextField(blank=True, verbose_name='trusted scopes')),
				('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_application_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
			],
			options={
				'verbose_name': 'app',
				'verbose_name_plural': 'apps',
			},
		),
		migrations.CreateModel(
			name='Code',
			fields=[
				('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
				('expires_at', models.DateTimeField()),
				('_scope', models.TextField(default='')),
				('nonce', models.CharField(blank=True, default='', max_length=255)),
				('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='RefreshToken',
			fields=[
				('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
				('expires_at', models.DateTimeField()),
				('_scope', models.TextField(default='')),
				('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='UserConsent',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('_scope', models.TextField(default='', verbose_name='scopes')),
				('date_given', models.DateTimeField(auto_now_add=True, verbose_name='date given')),
				('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
				('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openid_provider.App', verbose_name='app')),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
			],
			options={
				'verbose_name': 'user consent',
				'verbose_name_plural': 'user consents',
			},
		),
		migrations.AlterUniqueTogether(
			name='userconsent',
			unique_together=set([('user', 'app')]),
		),
	]
