# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('aiakos', '0002_oauth'),
		('openid_provider', '0006_v2'),
	]

	operations = [
		migrations.CreateModel(
			name='Client',
			fields=[
			],
			options={
				'proxy': True,
				'indexes': [],
			},
			bases=('aiakos.user',),
		),
	]
